FROM ubuntu:16.04

ENV DEBIAN_FRONTEND="noninteractive"

COPY * /tmp/

RUN cp /tmp/99fixbadproxy /etc/apt/apt.conf.d/99fixbadproxy && \
    bash /tmp/update_apt_source.sh && \
    apt-get -y install \
    tzdata \
    lsb-release \
    apt-utils \
    locales \
    apt-transport-https \
    debconf-utils \
    git \
    vim \
    wget \
    sudo && \
    dpkg-reconfigure locales && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*
