
FROM osrf/ros:kinetic-desktop-xenial

ENV DEBIAN_FRONTEND="noninteractive"\
    LANG="en_US.UTF-8" \
    LANGUAGE="en_US:en" \
    LC_ALL="en_US.UTF-8"

COPY * /tmp/

RUN bash /tmp/update_apt_ros_source.sh && \
    apt-get update -y && \
    apt-get -y install \
    apt-utils \
    apt-transport-https \
    debconf-utils \
    git \
    wget \
    sudo &&\
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*
